---
# Lab5
- name: Block 5-1
  block:
    - name: Create user and dir
      user:
        name: "{{ dest_user }}"
        password: "{{user_pass | password_hash('sha512')}}"
        createhome: yes
        shell: /bin/bash
  rescue: 
    - name: sendmail
      mail:
        host: "{{ mail_host }}"
        port: "{{ mail_port }}"
        sender: "{{ mail_sender }}"
        to: "{{ mail_to }}"
        subject: "{{ mail_subject }}"
        body: "{{ mail_body }}"    

- name: Block 5-2
  block:
    - name: install python
      package:
        name: pithon-pip
        state: latest

    - name: Intall docker-py
      pip:
        name: docker-py

    - name: Ensure docker service started
      systemd:
        name: docker
        state: started    
        enabled: true
    
    - name: Start nginx in container
      docker_container:
        name: nginx_container          
        image: nginx:latest
        state: started
  rescue:
    - name: Ups
      command: echo "UPS"
